export const gradeSectionMap = {
  "7": [
    "MAGALANG",
    "MAGITING",
    "MAKABANSA",
    "MAKA-DIYOS",
    "MAKAKALIKASAN",
    "MAKATAO",
    "MAKATARUNGAN",
    "MASIGASIG",
    "MATAPAT",
  ],
  "8": [
    "ALMARIO",
    "BALAGTAS",
    "BAUTISTA",
    "FLORENTINO",
    "HERNANDEZ",
    "JOAQUIN",
    "JOSE",
    "RECTO",
    "ROCES",
  ],
  "9": [
    "AGONCILLO",
    "AQUINO",
    "BURGOS",
    "DAGOHOY",
    "GOMEZ",
    "JAENA",
    "PATERNO",
    "PONCE",
    "SILANG",
  ],
  "10": [
    "ABUEVA",
    "ALCALA",
    "AMORSOLO",
    "CABRERA",
    "CAYABYAB",
    "EDADES",
    "FRANCISCO",
    "MANANSALA",
    "TOLENTINO",
  ],
};