import { KanbanIcon } from "lucide-react";

const questions = [
  {
    // Type With Voice and Slow Sample Question (Sundan niyo nalang for other questions)
    id: 1,
    type: "TypeWithVoiceAndSlow",
    question: null,
    image: null,
    choices: null,
    correctAnswer: "Dalawa",
    voice: "/assets/Voice/Number/dalawa.mp3",
  },
  {
    // Six Choices With Voice Sample Question
    id: 2,
    type: "SixChoicesWithVoice",
    question: "Kanin",
    choices: [
      { image: "/assets/ImageChoices/Gulay.png", value: "Utan" },
      { image: "/assets/ImageChoices/Kanin.png", value: "Kan on" },
      { image: "/assets/ImageChoices/Mantika.png", value: "Uwel" },
      { image: "/assets/ImageChoices/Kanan.png", value: "Tuo" },
      { image: "/assets/ImageChoices/Bahay.png", value: "Balay" },
      { image: "/assets/ImageChoices/Pera.png", value: "Kwarta" },
    ],
    correctAnswer: {
      image: "/assets/ImageChoices/Kanin.png",
      value: "Kan on",
    },
    image: null,
    voice: "/assets/Voice/Words/kanin.mp3",
  },
  {
    // Four Choices With Character And Voice Sample Question
    id: 3,
    type: "FourChoicesWithCharacterAndVoice",
    question: null,
    choices: [
      { value: "Napulo", voice: "/assets/Voice/CebuanoNumber/napulo.mp3" },
      { value: "Usa", voice: "/assets/Voice/CebuanoNumber/usa.mp3" },
      { value: "Unom", voice: "/assets/Voice/CebuanoNumber/unom.mp3" },
      { value: "Tulo", voice: "/assets/Voice/CebuanoNumber/tulo.mp3" },
    ],
    correctAnswer: "Tulo",
    image: "/assets/ImageChoices/Bluegirl1.png",
    voice: null,
  },
  {
    //Matching Words With Words Sample Question
    id: 4,
    type: "MatchingWordsWithWords",
    question: "Pindutin ang Magkapares.",
    choices: [
      { word1: "Kanin", word2: "Uwel" },
      { word1: "Bigas", word2: "Sud-an" },
      { word1: "Mantika", word2: "Kan on" },
      { word1: "Ulam", word2: "Bugas" },
    ],
    correctAnswer: [
      { word1: "Kanin", word2: "Kan on" },
      { word1: "Bigas", word2: "Bugas" },
      { word1: "Mantika", word2: "Uwel" },
      { word1: "Ulam", word2: "Sud-an" },
    ],
    image: null,
    voice: null,
  },
  {
    // Question With 3 Choices Sample Question
    id: 5,
    type: "QuestionWith3Choices",
    question: "Alin sa mga sumusunod ang Utan?",
    choices: [
      { image: "/assets/ImageChoices/Ulam.png", value: "Ulam" },
      { image: "/assets/ImageChoices/Gulay.png", value: "Gulay" },
      { image: "/assets/ImageChoices/Bigas.png", value: "Bigas" },
    ],
    correctAnswer: "Gulay",
    image: null,
    voice: null,
  },
  {
    //Drag And Drop 4 Choices With Voice Sample Question
    id: 6,
    type: "DragAndDrop4ChoicesWithVoice",
    question: "Bugas",
    choices: ["Bigas", "Ulam", "Gulay", "Kanin"],
    correctAnswer: "Bigas",
    image: null,
    voice: "/assets/Voice/CebuanoWords/bugas.mp3",
  },
  {
    //Matching Words With Image Sample Question
    // id: 7,
    // type: "MatchingWordsWithImage",
    // question: null,
    // choices: [
    //   { word: "Sud-an", image: "/assets/ImageChoices/Gulay.png" },
    //   { word: "Bugas", image: "/assets/ImageChoices/Kanin.png" },
    //   { word: "Kan on", image: "/assets/ImageChoices/Ulam.png" },
    //   { word: "Uwel", image: "/assets/ImageChoices/Bigas.png" },
    //   { word: "Utan", image: "/assets/ImageChoices/Mantika.png" },
    // ],
    // correctAnswer: [
    //   { word: "Utan", image: "/assets/ImageChoices/Gulay.png" },
    //   { word: "Kan on", image: "/assets/ImageChoices/Kanin.png" },
    //   { word: "Sud-an", image: "/assets/ImageChoices/Ulam.png" },
    //   { word: "Bugas", image: "/assets/ImageChoices/Bigas.png" },
    //   { word: "Uwel", image: "/assets/ImageChoices/Mantika.png" },
    // ],
    // image: null,
    // voice: null,

    // Question With 3 Choices Sample Question
    id: 7,
    type: "QuestionWith3Choices",
    question: "Alin sa mga sumusunod ang Kanan?",
    choices: [
      { image: "/assets/ImageChoices/Kanan.png", value: "Tuo" },
      { image: "/assets/ImageChoices/Bigas.png", value: "Bugas" },
      { image: "/assets/ImageChoices/Kaliwa.png", value: "Wala" },
    ],
    correctAnswer: "Tuo",
    image: null,
    voice: null,
  },
  {
    // Question with 4 Choices Sample Question
    // id: 8,
    // type: "QuestionWith4Choices",
    // question: "Alin sa mga ito ang Duha?",
    // choices: [
    //   { image: "/assets/ImageChoices/Two.png" },
    //   { image: "/assets/ImageChoices/Four.png" },
    //   { image: "/assets/ImageChoices/Eighth.png" },
    //   { image: "/assets/ImageChoices/Four.png" },
    // ],
    // correctAnswer: { image: "/assets/ImageChoices/Two.png" },
    // image: null,
    // voice: null,

    // Speech Mic With Voice Sample Question
    id: 8,
    type: "SpeechMicWithVoice",
    question: "Pera",
    choices: null,
    correctAnswer: "Pera",
    image: null,
    voice: "/assets/Voice/Words/pera.mp3",
  },
  {
    // Select 6 Choices With Voice And Slow Sample Question
    // id: 9,
    // type: "Select6ChoicesWithVoiceAndSlow",
    // question: "Pindutin and maririning mo.",
    // choices: ["Tuo", "Sud-an", "Balay", "Utan", "Uwel", "Wala"],
    // correctAnswer: "Balay",
    // image: null,
    // voice: "/assets/Voice/Words/bahay.mp3",

    // Six Choices With Voice Sample Question
    id: 9,
    type: "SixChoicesWithVoice",
    question: "Sud-an",
    choices: [
      { image: "/assets/ImageChoices/Kanan.png", value: "Kanan" },
      { image: "/assets/ImageChoices/Araw.png", value: "Araw" },
      { image: "/assets/ImageChoices/Bigas.png", value: "Bugas" },
      { image: "/assets/ImageChoices/Kanin.png", value: "Kanin" },
      { image: "/assets/ImageChoices/Kaliwa.png", value: "Kaliwa" },
      { image: "/assets/ImageChoices/Ulam.png", value: "Ulam" },
    ],
    correctAnswer: {
      image: "/assets/ImageChoices/Ulam.png",
      value: "Ulam",
    },
    image: null,
    voice: "/assets/Voice/CebuanoWords/sud-an.mp3",
  },
  {
    // Speech Mic With Voice Sample Question
    // id: 10,
    // type: "SpeechMicWithVoice",
    // question: "Pera",
    // choices: null,
    // correctAnswer: "Kwarta",
    // image: null,
    // voice: null,

    // Select 6 Choices With Voice And Slow Sample Question
    id: 10,
    type: "Select6ChoicesWithVoiceAndSlow",
    question: "Pindutin and maririning mo.",
    choices: ["Tuo", "Sud-an", "Balay", "Utan", "Uwel", "Wala"],
    correctAnswer: "Balay",
    image: null,
    voice: "/assets/Voice/CebuanoWords/balay.mp3",
  },
  {
    // Question With 3 Choices Sample Question
    id: 11,
    type: "QuestionWith3Choices",
    question: "Alin sa mga sumusunod ang Duha?",
    choices: [
      { image: "/assets/ImageChoices/Two.png", value: "Dalawa" },
      { image: "/assets/ImageChoices/Four.png", value: "Apat" },
      { image: "/assets/ImageChoices/Eighth.png", value: "Walo" },
    ],
    correctAnswer: "Dalawa",
    image: null,
    voice: null,
  },
  {
    id: 12,
    type: "TypeWithVoiceAndSlow",
    question: null,
    image: null,
    choices: null,
    correctAnswer: "Adlaw",
    voice: "/assets/Voice/CebuanoWords/adlaw.mp3",
  },
  {
    id: 13,
    type: "MatchingWordsWithWords",
    question: "Pindutin ang Magkapares.",
    choices: [
      { word1: "Wala", word2: "Araw" },
      { word1: "Tuo", word2: "Kaliwa" },
      { word1: "Balay", word2: "Kanan" },
      { word1: "Adlaw", word2: "Utan" },
      { word1: "Gulay", word2: "Bahay" },
    ],
    correctAnswer: [
      { word1: "Wala", word2: "Kaliwa" },
      { word1: "Tuo", word2: "Kanan" },
      { word1: "Balay", word2: "Bahay" },
      { word1: "Adlaw", word2: "Araw" },
      { word1: "Gulay", word2: "Utan" },
    ],
    image: null,
    voice: null,
  },
  {
    id: 14,
    type: "SpeechMicWithVoice",
    question: "Uwel",
    choices: null,
    correctAnswer: "U w e l",
    image: null,
    voice: "/assets/Voice/CebuanoWords/uwel.mp3",
  },
  {
    id: 15,
    type: "QuestionWith4Choices",
    question: "Alin sa mga sumusunod ang wala?",
    choices: [
      { image: "/assets/ImageChoices/Kanan.png", value: "Kanan" },
      { image: "/assets/ImageChoices/Bahay.png", value: "Bahay" },
      { image: "/assets/ImageChoices/Kaliwa.png", value: "Kaliwa" },
      { image: "/assets/ImageChoices/Gulay.png", value: "Gulay" },
    ],
    correctAnswer: "Kaliwa",
    image: null,
    voice: null,
  },
  {
    id: 16,
    type: "TypeWithVoiceAndSlow",
    question: null,
    image: null,
    choices: null,
    correctAnswer: "Pito",
    voice: "/assets/Voice/CebuanoNumber/pito.mp3",
  },
  {
    id: 17,
    type: "SixChoicesWithVoice",
    question: "Uwel",
    choices: [
      { image: "/assets/ImageChoices/Kanin.png", value: "Kanin" },
      { image: "/assets/ImageChoices/Kanan.png", value: "Kanan" },
      { image: "/assets/ImageChoices/Kaliwa.png", value: "Kaliwa" },
      { image: "/assets/ImageChoices/Mantika.png", value: "Mantika" },
      { image: "/assets/ImageChoices/Gulay.png", value: "Gulay" },
      { image: "/assets/ImageChoices/Bahay.png", value: "Bahay" },
    ],
    correctAnswer: {
      image: "/assets/ImageChoices/Mantika.png",
      value: "Mantika",
    },
    image: null,
    voice: "/assets/Voice/CebuanoWords/uwel.mp3",
  },
  {
    id: 18,
    type: "FourChoicesWithCharacterAndVoice",
    question: null,
    choices: [
      { value: "Pera", voice: "/assets/Voice/Words/pera.mp3" },
      { value: "Kaliwa", voice: "/assets/Voice/Words/kaliwa.mp3" },
      { value: "Kanan", voice: "/assets/Voice/Words/kanan.mp3" },
      { value: "Araw", voice: "/assets/Voice/Words/araw.mp3" },
    ],
    correctAnswer: "Pera",
    image: "/assets/ImageChoices/Redgirl1.png",
    voice: null,
  },
  {
    id: 19,
    type: "SpeechMicWithVoice",
    question: "Ulam",
    choices: null,
    correctAnswer: "Ulam",
    image: null,
    voice: "/assets/Voice/CebuanoWords/ulam.mp3",
  },
  {
    id: 20,
    type: "QuestionWith3Choices",
    question: "Alin sa mga sumusunod ang Araw?",
    choices: [
      { image: "/assets/ImageChoices/Pera.png", value: "Kwarta" },
      { image: "/assets/ImageChoices/Bahay.png", value: "Balay" },
      { image: "/assets/ImageChoices/Araw.png", value: "Adlaw" },
    ],
    correctAnswer: "Adlaw",
    image: null,
    voice: null,
  },
  {
    id: 21,
    type: "TypeWithVoiceAndSlow",
    question: null,
    image: null,
    choices: null,
    correctAnswer: "Lima",
    voice: "/assets/Voice/CebuanoNumber/lima.mp3",
  },
  {
    id: 22,
    type: "MatchingWordsWithWords",
    question: "Pindutin ang Magkapares.",
    choices: [
      { word1: "Duha", word2: "Walo" },
      { word1: "Lima", word2: "Isa" },
      { word1: "Napulo", word2: "Dalawa" },
      { word1: "Walo", word2: "Lima" },
      { word1: "Usa", word2: "Sampu" },
    ],
    correctAnswer: [
      { word1: "Duha", word2: "Dalawa" },
      { word1: "Lima", word2: "Lima" },
      { word1: "Napulo", word2: "Sampu" },
      { word1: "Walo", word2: "Walo" },
      { word1: "Usa", word2: "Isa" },
    ],
    image: null,
    voice: null,
  },
  {
    id: 23,
    type: "MatchingWordsWithWords",
    question: "Pindutin ang Magkapares.",
    choices: [
      { word1: "Tatlo", word2: "Siyam" },
      { word1: "Siyam", word2: "Tulo" },
      { word1: "Pito", word2: "Upat" },
      { word1: "Anim", word2: "Pito" },
      { word1: "Apat", word2: "Unom" },
    ],
    correctAnswer: [
      { word1: "Tatlo", word2: "Tulo" },
      { word1: "Siyam", word2: "Siyam" },
      { word1: "Pito", word2: "Pito" },
      { word1: "Anim", word2: "Unom" },
      { word1: "Apat", word2: "Upat" },
    ],
    image: null,
    voice: null,
  },
  {
    id: 24,
    type: "DragAndDrop4ChoicesWithVoice",
    question: "Gulay",
    choices: ["Utan", "Kwarta", "Balay", "Mantika"],
    correctAnswer: "Utan",
    image: null,
    voice: "/assets/Voice/Words/gulay.mp3",
  },
  {
    id: 25,
    type: "FourChoicesWithCharacterAndVoice",
    question: null,
    choices: [
      { value: "Bugas", voice: "/assets/Voice/CebuanoWords/bugas.mp3" },
      { value: "Sud-an", voice: "/assets/Voice/CebuanoWords/sud-an.mp3" },
      { value: "Uwel", voice: "/assets/Voice/CebuanoWords/uwel.mp3" },
      { value: "Kan on", voice: "/assets/Voice/CebuanoWords/kan on.mp3" },
    ],
    correctAnswer: "Uwel",
    image: "/assets/ImageChoices/Bluegirl2.png",
    voice: null,
  },
  {
    id: 26,
    type: "TypeWithVoiceAndSlow",
    question: null,
    image: null,
    choices: null,
    correctAnswer: "Kwarta",
    voice: "/assets/Voice/CebuanoWords/kwarta.mp3",
  },
  {
    id: 27,
    type: "DragAndDrop4ChoicesWithVoice",
    question: "Kaliwa",
    choices: ["Kwarta", "Tuo", "Balay", "Wala"],
    correctAnswer: "Wala",
    image: null,
    voice: "/assets/Voice/Words/kaliwa.mp3",
  },
  {
    id: 28,
    type: "FourChoicesWithCharacterAndVoice",
    question: null,
    choices: [
      { value: "Araw", voice: "/assets/Voice/Words/araw.mp3" },
      { value: "Kanan", voice: "/assets/Voice/Words/kanan.mp3" },
      { value: "Bahay", voice: "/assets/Voice/Words/bahay.mp3" },
      { value: "Pera", voice: "/assets/Voice/Words/pera.mp3" },
    ],
    correctAnswer: "Kanan",
    image: "/assets/ImageChoices/Redgirl2.png",
    voice: null,
  },
  {
    id: 29,
    type: "TypeWithVoiceAndSlow",
    question: null,
    image: null,
    choices: null,
    correctAnswer: "Tuo",
    voice: "/assets/Voice/CebuanoWords/tuo.mp3",
  },
  {
    id: 30,
    type: "Select6ChoicesWithVoiceAndSlow",
    question: "Pindutin and maririning mo.",
    choices: ["Usa", "Unom", "Siyam", "Upat", "Duha", "Tulo"],
    correctAnswer: "Unom",
    image: null,
    voice: "/assets/Voice/CebuanoNumber/unom.mp3",
  },
];

export default questions;
