import { KanbanIcon } from "lucide-react";

const questions = [
  {
    // Type With Voice and Slow Sample Question (Sundan niyo nalang for other questions)
    id: 1,
    type: "TypeWithVoiceAndSlow",
    question: null,
    image: null,
    choices: null,
    correctAnswer: "dalawa",
    voice: "/assets/Voice/Number/dalawa.mp3",
  },
  {
    // Six Choices With Voice Sample Question
    id: 2,
    type: "SixChoicesWithVoice",
    question: "kanin",
    choices: [
      { image: "/assets/ImageChoices/Gulay.png", value: "utan" },
      { image: "/assets/ImageChoices/Kanin.png", value: "kan on" },
      { image: "/assets/ImageChoices/Mantika.png", value: "uwel" },
      { image: "/assets/ImageChoices/Kanan.png", value: "tuo" },
      { image: "/assets/ImageChoices/Bahay.png", value: "balay" },
      { image: "/assets/ImageChoices/Pera.png", value: "kwarta" },
    ],
    correctAnswer: {
      image: "/assets/ImageChoices/Kanin.png",
      value: "kan on",
    },
    image: null,
    voice: "/assets/Voice/Words/kanin.mp3",
  },
  {
    // Four Choices With Character And Voice Sample Question
    id: 3,
    type: "FourChoicesWithCharacterAndVoice",
    question: null,
    choices: [
      { value: "napulo", voice: "/assets/Voice/CebuanoNumber/napulo.mp3" },
      { value: "usa", voice: "/assets/Voice/CebuanoNumber/usa.mp3" },
      { value: "unom", voice: "/assets/Voice/CebuanoNumber/unom.mp3" },
      { value: "tulo", voice: "/assets/Voice/CebuanoNumber/tulo.mp3" },
    ],
    correctAnswer: "tulo",
    image: "/assets/ImageChoices/Bluegirl1.png",
    voice: null,
  },
  {
    //Matching Words With Words Sample Question
    id: 4,
    type: "MatchingWordsWithWords",
    question: "Pindutin ang magkapares.",
    choices: [
      { word1: "kanin", word2: "uwel" },
      { word1: "bigas", word2: "sud-an" },
      { word1: "mantika", word2: "kan on" },
      { word1: "ulam", word2: "bugas" },
    ],
    correctAnswer: [
      { word1: "kanin", word2: "kan on" },
      { word1: "bigas", word2: "bugas" },
      { word1: "mantika", word2: "uwel" },
      { word1: "ulam", word2: "sud-an" },
    ],
    image: null,
    voice: null,
  },
  {
    // Question With 3 Choices Sample Question
    id: 5,
    type: "QuestionWith3Choices",
    question: "Alin sa mga sumusunod ang \"utan\"?",
    choices: [
      { image: "/assets/ImageChoices/Ulam.png", value: "ulam" },
      { image: "/assets/ImageChoices/Gulay.png", value: "gulay" },
      { image: "/assets/ImageChoices/Bigas.png", value: "bigas" },
    ],
    correctAnswer: "gulay",
    image: null,
    voice: null,
  },
  {
    //Drag And Drop 4 Choices With Voice Sample Question
    id: 6,
    type: "DragAndDrop4ChoicesWithVoice",
    question: "bugas",
    choices: ["bigas", "ulam", "gulay", "kanin"],
    correctAnswer: "bigas",
    image: null,
    voice: "/assets/Voice/CebuanoWords/bugas.mp3",
  },
  {
    //Matching Words With Image Sample Question
    // id: 7,
    // type: "MatchingWordsWithImage",
    // question: null,
    // choices: [
    //   { word: "Sud-an", image: "/assets/ImageChoices/Gulay.png" },
    //   { word: "Bugas", image: "/assets/ImageChoices/Kanin.png" },
    //   { word: "Kan on", image: "/assets/ImageChoices/Ulam.png" },
    //   { word: "Uwel", image: "/assets/ImageChoices/Bigas.png" },
    //   { word: "Utan", image: "/assets/ImageChoices/Mantika.png" },
    // ],
    // correctAnswer: [
    //   { word: "Utan", image: "/assets/ImageChoices/Gulay.png" },
    //   { word: "Kan on", image: "/assets/ImageChoices/Kanin.png" },
    //   { word: "Sud-an", image: "/assets/ImageChoices/Ulam.png" },
    //   { word: "Bugas", image: "/assets/ImageChoices/Bigas.png" },
    //   { word: "Uwel", image: "/assets/ImageChoices/Mantika.png" },
    // ],
    // image: null,
    // voice: null,

    // Question With 3 Choices Sample Question
    id: 7,
    type: "QuestionWith3Choices",
    question: "Alin sa mga sumusunod ang \"kanan\"?",
    choices: [
      { image: "/assets/ImageChoices/Kanan.png", value: "tuo" },
      { image: "/assets/ImageChoices/Bigas.png", value: "bugas" },
      { image: "/assets/ImageChoices/Kaliwa.png", value: "wala" },
    ],
    correctAnswer: "tuo",
    image: null,
    voice: null,
  },
  {
    // Question with 4 Choices Sample Question
    // id: 8,
    // type: "QuestionWith4Choices",
    // question: "Alin sa mga ito ang Duha?",
    // choices: [
    //   { image: "/assets/ImageChoices/Two.png" },
    //   { image: "/assets/ImageChoices/Four.png" },
    //   { image: "/assets/ImageChoices/Eighth.png" },
    //   { image: "/assets/ImageChoices/Four.png" },
    // ],
    // correctAnswer: { image: "/assets/ImageChoices/Two.png" },
    // image: null,
    // voice: null,

    // Speech Mic With Voice Sample Question
    id: 8,
    type: "SpeechMicWithVoice",
    question: "pera",
    choices: null,
    correctAnswer: "pera",
    image: null,
    voice: "/assets/Voice/Words/pera.mp3",
  },
  {
    // Select 6 Choices With Voice And Slow Sample Question
    // id: 9,
    // type: "Select6ChoicesWithVoiceAndSlow",
    // question: "Pindutin and maririning mo.",
    // choices: ["Tuo", "Sud-an", "Balay", "Utan", "Uwel", "Wala"],
    // correctAnswer: "Balay",
    // image: null,
    // voice: "/assets/Voice/Words/bahay.mp3",

    // Six Choices With Voice Sample Question
    id: 9,
    type: "SixChoicesWithVoice",
    question: "sud-an",
    choices: [
      { image: "/assets/ImageChoices/Kanan.png", value: "kanan" },
      { image: "/assets/ImageChoices/Araw.png", value: "araw" },
      { image: "/assets/ImageChoices/Bigas.png", value: "bugas" },
      { image: "/assets/ImageChoices/Kanin.png", value: "kanin" },
      { image: "/assets/ImageChoices/Kaliwa.png", value: "kaliwa" },
      { image: "/assets/ImageChoices/Ulam.png", value: "ulam" },
    ],
    correctAnswer: {
      image: "/assets/ImageChoices/Ulam.png",
      value: "ulam",
    },
    image: null,
    voice: "/assets/Voice/CebuanoWords/sud-an.mp3",
  },
  {
    id: 10,
    type: "Select6ChoicesWithVoiceAndSlow",
    question: "Pindutin and salitang maririnig mo.",
    choices: ["tuo", "sud-an", "balay", "utan", "uwel", "wala"],
    correctAnswer: "balay",
    image: null,
    voice: "/assets/Voice/CebuanoWords/balay.mp3",
  },
  {
    // Question With 3 Choices Sample Question
    id: 11,
    type: "QuestionWith3Choices",
    question: "Alin sa mga sumusunod ang \"duha\"?",
    choices: [
      { image: "/assets/ImageChoices/Two.png", value: "dalawa" },
      { image: "/assets/ImageChoices/Four.png", value: "apat" },
      { image: "/assets/ImageChoices/Eighth.png", value: "walo" },
    ],
    correctAnswer: "dalawa",
    image: null,
    voice: null,
  },
  {
    id: 12,
    type: "TypeWithVoiceAndSlow",
    question: null,
    image: null,
    choices: null,
    correctAnswer: "adlaw",
    voice: "/assets/Voice/CebuanoWords/adlaw.mp3",
  },
  {
    id: 13,
    type: "MatchingWordsWithWords",
    question: "Pindutin ang magkapares.",
    choices: [
      { word1: "wala", word2: "araw" },
      { word1: "tuo", word2: "kaliwa" },
      { word1: "balay", word2: "kanan" },
      { word1: "adlaw", word2: "utan" },
      { word1: "gulay", word2: "bahay" },
    ],
    correctAnswer: [
      { word1: "wala", word2: "kaliwa" },
      { word1: "tuo", word2: "kanan" },
      { word1: "balay", word2: "bahay" },
      { word1: "adlaw", word2: "araw" },
      { word1: "gulay", word2: "utan" },
    ],
    image: null,
    voice: null,
  },
  {
    id: 14,
    type: "SpeechMicWithVoice",
    question: "utan",
    choices: null,
    correctAnswer: "utan",
    image: null,
    voice: "/assets/Voice/CebuanoWords/utan.mp3",
  },
  {
    id: 15,
    type: "QuestionWith4Choices",
    question: "Alin sa mga sumusunod ang \"wala\"?",
    choices: [
      { image: "/assets/ImageChoices/Kanan.png", value: "kanan" },
      { image: "/assets/ImageChoices/Bahay.png", value: "bahay" },
      { image: "/assets/ImageChoices/Kaliwa.png", value: "kaliwa" },
      { image: "/assets/ImageChoices/Gulay.png", value: "gulay" },
    ],
    correctAnswer: "kaliwa",
    image: null,
    voice: null,
  },
  {
    id: 16,
    type: "TypeWithVoiceAndSlow",
    question: null,
    image: null,
    choices: null,
    correctAnswer: "pito",
    voice: "/assets/Voice/CebuanoNumber/pito.mp3",
  },
  {
    id: 17,
    type: "SixChoicesWithVoice",
    question: "uwel",
    choices: [
      { image: "/assets/ImageChoices/Kanin.png", value: "kanin" },
      { image: "/assets/ImageChoices/Kanan.png", value: "kanan" },
      { image: "/assets/ImageChoices/Kaliwa.png", value: "kaliwa" },
      { image: "/assets/ImageChoices/Mantika.png", value: "mantika" },
      { image: "/assets/ImageChoices/Gulay.png", value: "gulay" },
      { image: "/assets/ImageChoices/Bahay.png", value: "bahay" },
    ],
    correctAnswer: {
      image: "/assets/ImageChoices/Mantika.png",
      value: "mantika",
    },
    image: null,
    voice: "/assets/Voice/CebuanoWords/uwel.mp3",
  },
  {
    id: 18,
    type: "FourChoicesWithCharacterAndVoice",
    question: null,
    choices: [
      { value: "pera", voice: "/assets/Voice/Words/pera.mp3" },
      { value: "kaliwa", voice: "/assets/Voice/Words/kaliwa.mp3" },
      { value: "kanan", voice: "/assets/Voice/Words/kanan.mp3" },
      { value: "araw", voice: "/assets/Voice/Words/araw.mp3" },
    ],
    correctAnswer: "pera",
    image: "/assets/ImageChoices/Redgirl1.png",
    voice: null,
  },
  {
    id: 19,
    type: "SpeechMicWithVoice",
    question: "ulam",
    choices: null,
    correctAnswer: "ulam",
    image: null,
    voice: "/assets/Voice/CebuanoWords/ulam.mp3",
  },
  {
    id: 20,
    type: "QuestionWith3Choices",
    question: "Alin sa mga sumusunod ang \"araw\"?",
    choices: [
      { image: "/assets/ImageChoices/Pera.png", value: "kwarta" },
      { image: "/assets/ImageChoices/Bahay.png", value: "balay" },
      { image: "/assets/ImageChoices/Araw.png", value: "adlaw" },
    ],
    correctAnswer: "adlaw",
    image: null,
    voice: null,
  },
  {
    id: 21,
    type: "TypeWithVoiceAndSlow",
    question: null,
    image: null,
    choices: null,
    correctAnswer: "lima",
    voice: "/assets/Voice/CebuanoNumber/lima.mp3",
  },
  {
    id: 22,
    type: "MatchingWordsWithWords",
    question: "Pindutin ang magkapares.",
    choices: [
      { word1: "duha", word2: "walo" },
      { word1: "lima", word2: "isa" },
      { word1: "napulo", word2: "dalawa" },
      { word1: "walo", word2: "lima" },
      { word1: "usa", word2: "sampu" },
    ],
    correctAnswer: [
      { word1: "duha", word2: "dalawa" },
      { word1: "lima", word2: "lima" },
      { word1: "napulo", word2: "sampu" },
      { word1: "walo", word2: "walo" },
      { word1: "usa", word2: "isa" },
    ],
    image: null,
    voice: null,
  },
  {
    id: 23,
    type: "MatchingWordsWithWords",
    question: "Pindutin ang magkapares.",
    choices: [
    { word1: "tatlo", word2: "siyam" },
    { word1: "siyam", word2: "tulo" },
    { word1: "pito", word2: "upat" },
    { word1: "anim", word2: "pito" },
    { word1: "apat", word2: "unom" },
  ],
  correctAnswer: [
    { word1: "tatlo", word2: "tulo" },
    { word1: "siyam", word2: "siyam" },
    { word1: "pito", word2: "pito" },
    { word1: "anim", word2: "unom" },
    { word1: "apat", word2: "upat" },
  ],
    image: null,
    voice: null,
  },
  {
    id: 24,
    type: "DragAndDrop4ChoicesWithVoice",
    question: "gulay",
    choices: ["utan", "kwarta", "balay", "mantika"],
    correctAnswer: "utan",
    image: null,
    voice: "/assets/Voice/Words/gulay.mp3",
  },
  {
    id: 25,
    type: "FourChoicesWithCharacterAndVoice",
    question: null,
    choices: [
      { value: "bugas", voice: "/assets/Voice/CebuanoWords/bugas.mp3" },
      { value: "sud-an", voice: "/assets/Voice/CebuanoWords/sud-an.mp3" },
      { value: "uwel", voice: "/assets/Voice/CebuanoWords/uwel.mp3" },
      { value: "kan on", voice: "/assets/Voice/CebuanoWords/kan on.mp3" },
    ],
    correctAnswer: "uwel",
    image: "/assets/ImageChoices/Bluegirl2.png",
    voice: null,
  },
  {
    id: 26,
    type: "TypeWithVoiceAndSlow",
    question: null,
    image: null,
    choices: null,
    correctAnswer: "kwarta",
    voice: "/assets/Voice/CebuanoWords/kwarta.mp3",
  },
  {
    id: 27,
    type: "DragAndDrop4ChoicesWithVoice",
    question: "kaliwa",
    choices: ["kwarta", "tuo", "balay", "wala"],
    correctAnswer: "wala",
    image: null,
    voice: "/assets/Voice/Words/kaliwa.mp3",
  },
  {
    id: 28,
    type: "FourChoicesWithCharacterAndVoice",
    question: null,
    choices: [
      { value: "araw", voice: "/assets/Voice/Words/araw.mp3" },
      { value: "kanan", voice: "/assets/Voice/Words/kanan.mp3" },
      { value: "bahay", voice: "/assets/Voice/Words/bahay.mp3" },
      { value: "pera", voice: "/assets/Voice/Words/pera.mp3" },
    ],
    correctAnswer: "kanan",
    image: "/assets/ImageChoices/Redgirl2.png",
    voice: null,
  },
  {
    id: 29,
    type: "TypeWithVoiceAndSlow",
    question: null,
    image: null,
    choices: null,
    correctAnswer: "tuo",
    voice: "/assets/Voice/CebuanoWords/tuo.mp3",
  },
  {
    id: 30,
    type: "Select6ChoicesWithVoiceAndSlow",
    question: "Pindutin and maririnig mo.",
    choices: ["usa", "unom", "siyam", "upat", "duha", "tulo"],
    correctAnswer: "unom",
    image: null,
    voice: "/assets/Voice/CebuanoNumber/unom.mp3",
  },
];

export default questions;
