import { KanbanIcon } from "lucide-react";

const questions = [
  {
    // Type With Voice and Slow Sample Question (Sundan niyo nalang for other questions)
    id: 1,
    type: "TypeWithVoiceAndSlow",
    question: null,
    image: null,
    choices: null,
    correctAnswer: "Dalawa",
    voice: "/assets/Voice/Number/dalawa.mp3",
  },
  {
    // Six Choices With Voice Sample Question
    id: 2,
    type: "SixChoicesWithVoice",
    question: "Kanin",
    choices: [
      { image: "/assets/ImageChoices/Gulay.png", value: "Utan" },
      { image: "/assets/ImageChoices/Kanin.png", value: "Kan on" },
      { image: "/assets/ImageChoices/Mantika.png", value: "Uwel" },
      { image: "/assets/ImageChoices/Bata.png", value: "Tuo" },
      { image: "/assets/ImageChoices/Bahay.png", value: "Balay" },
      { image: "/assets/ImageChoices/Pera.png", value: "Kwarta" },
    ],
    correctAnswer: {
      image: "/assets/ImageChoices/Kanin.png",
      value: "Kan on",
    },
    image: null,
    voice: "/assets/Voice/Words/kanin.mp3",
  },
  {
    // Four Choices With Character And Voice Sample Question
    id: 3,
    type: "FourChoicesWithCharacterAndVoice",
    question: null,
    choices: [
      { value: "Napulo", voice: "/assets/Voice/Number/sampo.mp3" },
      { value: "Usa", voice: "/assets/Voice/Number/isa.mp3" },
      { value: "Unom", voice: "/assets/Voice/Number/anim.mp3" },
      { value: "Tulo", voice: "/assets/Voice/Number/tatlo.mp3" },
    ],
    correctAnswer: "Tulo",
    image: null,
    voice: null,
  },
  {
    //Matching Words With Words Sample Question
    id: 4,
    type: "MatchingWordsWithWords",
    question: "Match the words.",
    choices: [
      { word1: "Kanin", word2: "Bugas" },
      { word1: "Bigas", word2: "Sud-an" },
      { word1: "Mantika", word2: "Kan on" },
      { word1: "Ulam", word2: "Utan" },
      { word1: "Gulay", word2: "Uwel" },
    ],
    correctAnswer: [
      { word1: "Kanin", word2: "Kan on" },
      { word1: "Bigas", word2: "Bugas" },
      { word1: "Mantika", word2: "Uwel" },
      { word1: "Ulam", word2: "Sud-an" },
      { word1: "Gulay", word2: "Utan" },
    ],
    image: null,
    voice: null,
  },
  {
    // Question With 3 Choices Sample Question
    id: 5,
    type: "QuestionWith3Choices",
    question: "Alin sa mga sumusunod ang Utan?",
    choices: [
      { image: "/assets/ImageChoices/Ulam.png", value: "Ulam" },
      { image: "/assets/ImageChoices/Gulay.png", value: "Gulay" },
      { image: "/assets/ImageChoices/Bigas.png", value: "Bigas" },
    ],
    correctAnswer: "Gulay",
    image: null,
    voice: null,
  },
  {
    //Drag And Drop 4 Choices With Voice Sample Question
    id: 6,
    type: "DragAndDrop4ChoicesWithVoice",
    question: "Bugas",
    choices: ["Bigas", "Ulam", "Gulay", "Kanin"],
    correctAnswer: "Kwarta",
    image: null,
    voice: "/assets/Voice/Words/bigas.mp3",
  },
  {
    //Matching Words With Image Sample Question
    // id: 7,
    // type: "MatchingWordsWithImage",
    // question: null,
    // choices: [
    //   { word: "Sud-an", image: "/assets/ImageChoices/Gulay.png" },
    //   { word: "Bugas", image: "/assets/ImageChoices/Kanin.png" },
    //   { word: "Kan on", image: "/assets/ImageChoices/Ulam.png" },
    //   { word: "Uwel", image: "/assets/ImageChoices/Bigas.png" },
    //   { word: "Utan", image: "/assets/ImageChoices/Mantika.png" },
    // ],
    // correctAnswer: [
    //   { word: "Utan", image: "/assets/ImageChoices/Gulay.png" },
    //   { word: "Kan on", image: "/assets/ImageChoices/Kanin.png" },
    //   { word: "Sud-an", image: "/assets/ImageChoices/Ulam.png" },
    //   { word: "Bugas", image: "/assets/ImageChoices/Bigas.png" },
    //   { word: "Uwel", image: "/assets/ImageChoices/Mantika.png" },
    // ],
    // image: null,
    // voice: null,

    // Question With 3 Choices Sample Question
    id: 7,
    type: "QuestionWith3Choices",
    question: "Alin sa mga sumusunod ang Kanan?",
    choices: [
      { image: "/assets/ImageChoices/Bata.png", value: "Tuo" },
      { image: "/assets/ImageChoices/Bigas.png", value: "Bugas" },
      { image: "/assets/ImageChoices/Kaliwa.png", value: "Wala" },
    ],
    correctAnswer: "Tuo",
    image: null,
    voice: null,
  },
  {
    // Question with 4 Choices Sample Question
    // id: 8,
    // type: "QuestionWith4Choices",
    // question: "Alin sa mga ito ang Duha?",
    // choices: [
    //   { image: "/assets/ImageChoices/Two.png" },
    //   { image: "/assets/ImageChoices/Four.png" },
    //   { image: "/assets/ImageChoices/Eighth.png" },
    //   { image: "/assets/ImageChoices/Four.png" },
    // ],
    // correctAnswer: { image: "/assets/ImageChoices/Two.png" },
    // image: null,
    // voice: null,

    // Speech Mic With Voice Sample Question
    id: 8,
    type: "SpeechMicWithVoice",
    question: "Pera",
    choices: null,
    correctAnswer: "Kwarta",
    image: null,
    voice: null,
  },
  {
    // Select 6 Choices With Voice And Slow Sample Question
    // id: 9,
    // type: "Select6ChoicesWithVoiceAndSlow",
    // question: "Pindutin and maririning mo.",
    // choices: ["Tuo", "Sud-an", "Balay", "Utan", "Uwel", "Wala"],
    // correctAnswer: "Balay",
    // image: null,
    // voice: "/assets/Voice/Words/bahay.mp3",

    // Six Choices With Voice Sample Question
    id: 9,
    type: "SixChoicesWithVoice",
    question: "Sud-an",
    choices: [
      { image: "/assets/ImageChoices/Bata.png", value: "Kanan" },
      { image: "/assets/ImageChoices/Araw.png", value: "Araw" },
      { image: "/assets/ImageChoices/Bigas.png", value: "Bugas" },
      { image: "/assets/ImageChoices/Kanin.png", value: "Kanin" },
      { image: "/assets/ImageChoices/Kaliwa.png", value: "Kaliwa" },
      { image: "/assets/ImageChoices/Ulam.png", value: "Ulam" },
    ],
    correctAnswer: {
      image: "/assets/ImageChoices/Ulam.png",
      value: "Ulam",
    },
    image: null,
    voice: "/assets/Voice/Words/ulam.mp3",
  },
  {
    // Speech Mic With Voice Sample Question
    // id: 10,
    // type: "SpeechMicWithVoice",
    // question: "Pera",
    // choices: null,
    // correctAnswer: "Kwarta",
    // image: null,
    // voice: null,

    // Select 6 Choices With Voice And Slow Sample Question
    id: 10,
    type: "Select6ChoicesWithVoiceAndSlow",
    question: "Pindutin and maririning mo.",
    choices: ["Tuo", "Sud-an", "Balay", "Utan", "Uwel", "Wala"],
    correctAnswer: "Balay",
    image: null,
    voice: "/assets/Voice/Words/bahay.mp3",
  },
  {
    // Question With 3 Choices Sample Question
    id: 11,
    type: "QuestionWith3Choices",
    question: "Alin sa mga sumusunod ang Duha?",
    choices: [
      { image: "/assets/ImageChoices/Two.png", value: "Two" },
      { image: "/assets/ImageChoices/Four.png", value: "Four" },
      { image: "/assets/ImageChoices/Eighth.png", value: "Eighth" },
    ],
    correctAnswer: "Two",
    image: null,
    voice: null,
  },
  {
    id: 12,
    type: "TypeWithVoiceAndSlow",
    question: null,
    image: null,
    choices: null,
    correctAnswer: "Dalawa",
    voice: "/assets/Voice/Number/dalawa.mp3",
  },
  {
    id: 13,
    type: "TypeWithVoiceAndSlow",
    question: null,
    image: null,
    choices: null,
    correctAnswer: "Dalawa",
    voice: "/assets/Voice/Number/dalawa.mp3",
  },
  {
    id: 14,
    type: "TypeWithVoiceAndSlow",
    question: null,
    image: null,
    choices: null,
    correctAnswer: "Dalawa",
    voice: "/assets/Voice/Number/dalawa.mp3",
  },
  {
    id: 15,
    type: "TypeWithVoiceAndSlow",
    question: null,
    image: null,
    choices: null,
    correctAnswer: "Dalawa",
    voice: "/assets/Voice/Number/dalawa.mp3",
  },
  {
    id: 16,
    type: "TypeWithVoiceAndSlow",
    question: null,
    image: null,
    choices: null,
    correctAnswer: "Dalawa",
    voice: "/assets/Voice/Number/dalawa.mp3",
  },
  {
    id: 17,
    type: "TypeWithVoiceAndSlow",
    question: null,
    image: null,
    choices: null,
    correctAnswer: "Dalawa",
    voice: "/assets/Voice/Number/dalawa.mp3",
  },
  {
    id: 18,
    type: "TypeWithVoiceAndSlow",
    question: null,
    image: null,
    choices: null,
    correctAnswer: "Dalawa",
    voice: "/assets/Voice/Number/dalawa.mp3",
  },
  {
    id: 19,
    type: "TypeWithVoiceAndSlow",
    question: null,
    image: null,
    choices: null,
    correctAnswer: "Dalawa",
    voice: "/assets/Voice/Number/dalawa.mp3",
  },
  {
    id: 20,
    type: "TypeWithVoiceAndSlow",
    question: null,
    image: null,
    choices: null,
    correctAnswer: "Dalawa",
    voice: "/assets/Voice/Number/dalawa.mp3",
  },
  {
    id: 21,
    type: "TypeWithVoiceAndSlow",
    question: null,
    image: null,
    choices: null,
    correctAnswer: "Dalawa",
    voice: "/assets/Voice/Number/dalawa.mp3",
  },
  {
    id: 22,
    type: "TypeWithVoiceAndSlow",
    question: null,
    image: null,
    choices: null,
    correctAnswer: "Dalawa",
    voice: "/assets/Voice/Number/dalawa.mp3",
  },
  {
    id: 23,
    type: "TypeWithVoiceAndSlow",
    question: null,
    image: null,
    choices: null,
    correctAnswer: "Dalawa",
    voice: "/assets/Voice/Number/dalawa.mp3",
  },
  {
    id: 24,
    type: "TypeWithVoiceAndSlow",
    question: null,
    image: null,
    choices: null,
    correctAnswer: "Dalawa",
    voice: "/assets/Voice/Number/dalawa.mp3",
  },
  {
    id: 25,
    type: "TypeWithVoiceAndSlow",
    question: null,
    image: null,
    choices: null,
    correctAnswer: "Dalawa",
    voice: "/assets/Voice/Number/dalawa.mp3",
  },
  {
    id: 26,
    type: "TypeWithVoiceAndSlow",
    question: null,
    image: null,
    choices: null,
    correctAnswer: "Dalawa",
    voice: "/assets/Voice/Number/dalawa.mp3",
  },
  {
    id: 27,
    type: "TypeWithVoiceAndSlow",
    question: null,
    image: null,
    choices: null,
    correctAnswer: "Dalawa",
    voice: "/assets/Voice/Number/dalawa.mp3",
  },
  {
    id: 28,
    type: "TypeWithVoiceAndSlow",
    question: null,
    image: null,
    choices: null,
    correctAnswer: "Dalawa",
    voice: "/assets/Voice/Number/dalawa.mp3",
  },
  {
    id: 29,
    type: "TypeWithVoiceAndSlow",
    question: null,
    image: null,
    choices: null,
    correctAnswer: "Dalawa",
    voice: "/assets/Voice/Number/dalawa.mp3",
  },
  {
    id: 30,
    type: "TypeWithVoiceAndSlow",
    question: null,
    image: null,
    choices: null,
    correctAnswer: "Dalawa",
    voice: "/assets/Voice/Number/dalawa.mp3",
  },
];

export default questions;
