import { KanbanIcon } from "lucide-react";

const questionsl2 = [
{
    id: 1,
    type: "DragAndDrop4ChoicesWithVoice",
    question: "Kanus-a?",
    choices: ["Ilan?", "Kailan?", "Saan?", "Ano?"],
    correctAnswer: "Kailan?",
    image: null,
    voice: "/assets/Voice/CebuanoLevel2/kanus-a.mp3",
  },
  {
    id: 2,
    type: "QuestionWith4ChoiceswithVoice",
    question: "Daghang Salamat",
    choices: [
      { image: "/assets/ImageChoices/glassesboy1.png", value: "Maraming Salamat" },
      { image: "/assets/ImageChoices/glassesboy2.png", value: "Walang Anuman" },
      { image: "/assets/ImageChoices/glassesboy3.png", value: "Patawad/Paumanhin" },
      { image: "/assets/ImageChoices/glassesboy4.png", value: "Pasuyo/Pakiusap" },
    ],
    correctAnswer: "Maraming Salamat",
    image: null,
    voice: "/assets/Voice/CebuanoLevel2/daghangsalamat.mp3",
  },
  {
    id: 3,
    type: "SpeechMicWithVoice",
    question: "Magandang Tanghali!",
    choices: null,
    correctAnswer: "Magandang Tanghali",
    image: null,
    voice: "/assets/Voice/TagalogLevel2/magandangtanghali.mp3",
  },
  {
    id: 4,
    type: "QuestionWith4ChoiceswithVoice",
    question: "Maayong Buntag!",
    choices: [
      { image: "/assets/ImageChoices/Hapon.png", value: "Magandang Hapon!" },
      { image: "/assets/ImageChoices/Umaga.png", value: "Magandang Umaga!" },
      { image: "/assets/ImageChoices/Tanghali.png", value: "Magandang Tanghali!" },
      { image: "/assets/ImageChoices/Gabi.png", value: "Magandang Gabi!" },
    ],
    correctAnswer: "Magandang Umaga!",
    image: null,
    voice: "/assets/Voice/CebuanoLevel2/maayongbuntag.mp3",
  },
  {
    id: 5,
    type: "DragAndDrop4ChoicesWithVoice",
    question: "Taga saan ka?",
    choices: ["Unsa imong ngalan?", "Taga asa ka?", "Asa ka muadto?", "Asa dapit ang tindahan?"],
    correctAnswer: "Taga asa ka?",
    image: null,
    voice: "/assets/Voice/TagalogLevel2/tagasaanka.mp3",
  },
  {
    id: 6,
    type: "MatchingWordsWithWords",
    question: "Pindutin ang Magkapares.",
    choices: [
      { word1: "saan", word2: "pila" },
      { word1: "kanino", word2: "kinsa" },
      { word1: "ilan", word2: "asa" },
      { word1: "sino", word2: "kakinsa" },
      { word1: "kailan", word2: "unsa" },
      { word1: "ano", word2: "kanus-a" },
    ],
    correctAnswer: [
      { word1: "saan", word2: "asa" },
      { word1: "kanino", word2: "kakinsa" },
      { word1: "ilan", word2: "pila" },
      { word1: "sino", word2: "kinsa" },
      { word1: "kailan", word2: "kanus-a" },
      { word1: "ano", word2: "unsa" },
    ],
    image: null,
    voice: null,
  },
  {
    id: 7,
    type: "TypeWithVoiceAndSlow",
    question: null,
    image: null,
    choices: null,
    correctAnswer: "Mag-iingat ka",
    voice: "/assets/Voice/TagalogLevel2/magiingatka.mp3",
  },
  {
    id: 8,
    type: "QuestionWith4ChoiceswithVoice",
    question: "Walang Anuman",
    choices: [
      { image: "/assets/ImageChoices/glassesboy3.png", value: "Pasayloa" },
      { image: "/assets/ImageChoices/glassesboy1.png", value: "Daghang Salamat" },
      { image: "/assets/ImageChoices/glassesboy4.png", value: "Palihog" },
      { image: "/assets/ImageChoices/glassesboy2.png", value: "Walay Sapayan" },
    ],
    correctAnswer: "Walay Sapayan",
    image: null,
    voice: "/assets/Voice/TagalogLevel2/walanganuman.mp3",
  },
  {
    id: 9,
    type: "DragAndDrop4ChoicesWithVoice",
    question: "Natutuwa akong makilala ka!",
    choices: ["Nalipay ko nga nakaila tika!", "Asa dapit ang tindahan?", "Pag-amping!", "Puwede mangutana?"],
    correctAnswer: "Nalipay ko nga nakaila tika!",
    image: null,
    voice: "/assets/Voice/TagalogLevel2/makilalaka.mp3",
  },
  {
    id: 10,
    type: "Select6Choices",
    question: "Alin sa mga sumusunod ang \"kakinsa\"?",
    choices: ["saan", "sino", "kailan", "kanino", "ilan", "ano"],
    correctAnswer: "kanino",
    image: null,
    voice: null,
  },
  {
    id: 11,
    type: "MatchingWordsWithWords",
    question: "Pindutin ang magkapares.",
    choices: [
      { word1: "Magandang Gabi", word2: "Maayong Udto" },
      { word1: "Magandang Umaga", word2: "Maayong Gabii" },
      { word1: "Magandang Tanghali", word2: "Maayong Hapon" },
      { word1: "Magandang Hapon", word2: "Maayong Buntag" },
    ],
    correctAnswer: [
      { word1: "Magandang Gabi", word2: "Maayong Gabii" },
      { word1: "Magandang Umaga", word2: "Maayong Buntag" },
      { word1: "Magandang Tanghali", word2: "Maayong Udto" },
      { word1: "Magandang Hapon", word2: "Maayong Hapon" },
    ],
    image: null,
    voice: null,
  },
  {
    id: 12,
    type: "Select6ChoicesWithVoiceAndSlow",
    question: "Piliin ang iyong narinig.",
    choices: ["kanino", "sino", "kailan", "ano"],
    correctAnswer: "kanino",
    image: null,
    voice: "/assets/Voice/TagalogLevel2/kanino.mp3",
  },
  {
    id: 13,
    type: "QuestionWith4ChoicesnoImage",
    question: "Pakiusap",
    choices: ["Walay sapayan", "Daghang Salamat", "Pasayloa", "Palihog"],
    correctAnswer: "Palihog",
    image: null,
    voice: "/assets/Voice/TagalogLevel2/pakiusap.mp3",
  },
  {
    id: 14,
    type: "QuestionWith4Choices",
    question: "Alin sa mga sumusunod ang \"udto\"?",
    choices: [
      { image: "/assets/ImageChoices/Gabi.png", value: "gabii" },
      { image: "/assets/ImageChoices/Tanghali.png", value: "buntag" },
      { image: "/assets/ImageChoices/Umaga.png", value: "udto" },
      { image: "/assets/ImageChoices/Hapon.png", value: "hapon" },
    ],
    correctAnswer: "udto",
    image: null,
    voice: null,
  },
  {
    id: 15,
    type: "TypeWithVoiceAndSlow",
    question: null,
    image: null,
    choices: null,
    correctAnswer: "asa",
    voice: "/assets/Voice/CebuanoLevel2/asa.mp3",
  },
  {
    id: 16,
    type: "Select6Choices",
    question: "Alin sa mga sumusunod ang \"mag-ingat ka\"?",
    choices: ["nalipay ko nga nakaila tika", "puwede mangutana?", "pag-amping", "unsa imong ngalan?", "taga asa ka?", "asa ka muadto?"],
    correctAnswer: "pag-amping",
    image: null,
    voice: null,
  },
  {
    id: 17,
    type: "DragAndDrop4ChoicesWithVoice",
    question: "Pasayloa",
    choices: ["Pasuyo/Pakiusap", "Maraming Salamat", "Patawad/Paumanhin", "Walang Anuman"],
    correctAnswer: "Patawad/Paumanhin",
    image: null,
    voice: "/assets/Voice/CebuanoLevel2/pasayloa.mp3",
  },
  {
    id: 18,
    type: "FourChoicesWithCharacterAndVoice",
    question: null,
    choices: [
      { value: "gabi", voice: "/assets/Voice/TagalogLevel2/pera.mp3" },
      { value: "hapon", voice: "/assets/Voice/Words/kaliwa.mp3" },
      { value: "umaga", voice: "/assets/Voice/Words/kanan.mp3" },
      { value: "tanghali", voice: "/assets/Voice/Words/araw.mp3" },
    ],
    correctAnswer: "gabi",
    image: "/assets/ImageChoices/talkingboy2.png",
    voice: null,
  },
  {
    id: 19,
    type: "QuestionWith4ChoicesnoImage",
    question: "Asa dapit ang tindahan?",
    choices: ["Anong pangalan mo?", "Saan banda ang tindahan?", "Saan ka pupunta?", "Puwede bang magtanong?"],
    correctAnswer: "Saan banda ang tindahan?",
    image: null,
    voice: "/assets/Voice/CebuanoLevel2/asadapitangtindahan.mp3",
  },
  {
    id: 20,
    type: "SpeechMicWithVoice",
    question: "Asa ka muadto?",
    choices: null,
    correctAnswer: "Asa ka muadto",
    image: null,
    voice: "/assets/Voice/CebuanoLevel2/muadto.mp3",
  },
  {
    id: 21,
    type: "DragAndDrop4ChoicesWithVoice",
    question: "Unsa imong ngalan?",
    choices: ["Puwede bang magtanong?", "Taga saan ka?", "Saan ka pupunta?", "Anong pangalan mo?"],
    correctAnswer: "Anong pangalan mo?",
    image: null,
    voice: "/assets/Voice/CebuanoLevel2/unsaimongngalan.mp3",
  },
  {
    id: 22,
    type: "TypeWithVoiceAndSlow",
    question: null,
    image: null,
    choices: null,
    correctAnswer: "palihog",
    voice: "/assets/Voice/CebuanoLevel2/palihog.mp3",
  },
  {
    id: 23,
    type: "FourChoicesWithCharacterAndVoice",
    question: null,
    choices: [
      { value: "Maraming Salamat", voice: "/assets/Voice/TagalogLevel2/maramingsalamat.mp3" },
      { value: "Pasuyo/ Pakiusap", voice: "/assets/Voice/TagalogLevel2/pakiusap.mp3" },
      { value: "Walang anuman", voice: "/assets/Voice/TagalogLevel2/walanganuman.mp3" },
      { value: "Patawad/ Paumanhin", voice: "/assets/Voice/TagalogLevel2/patawad.mp3" },
    ],
    correctAnswer: "Walang anuman",
    image: "/assets/ImageChoices/talkingboy1.png",
    voice: null,
  },
  {
    id: 24,
    type: "DragAndDrop4ChoicesWithVoice",
    question: "Saan banda ang tindahan?",
    choices: ["Asa dapit ang tindahan?", "Unsa imong ngalan?", "Taga asa ka?", "Asa ka muadto?"],
    correctAnswer: "Asa dapit ang tindahan?",
    image: null,
    voice: "/assets/Voice/TagalogLevel2/tindahan.mp3",
  },
  {
    id: 25,
    type: "Select6ChoicesWithVoiceAndSlow",
    question: "Piliin ang iyong narinig.",
    choices: ["unsa", "asa", "kinsa", "kakinsa"],
    correctAnswer: "kinsa",
    image: null,
    voice: "/assets/Voice/CebuanoLevel2/kinsa.mp3",
  },
 ]


export default questionsl2;